# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hzq/face_hzq/face_landmark_prj/PFLD-pytorch-master/Face_Align_PFLD_ncnn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hzq/face_hzq/face_landmark_prj/PFLD-pytorch-master/Face_Align_PFLD_ncnn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzq/face_hzq/face_landmark_prj/PFLD-pytorch-master/Face_Align_PFLD_ncnn/CMakeFiles /home/hzq/face_hzq/face_landmark_prj/PFLD-pytorch-master/Face_Align_PFLD_ncnn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzq/face_hzq/face_landmark_prj/PFLD-pytorch-master/Face_Align_PFLD_ncnn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FaceLandmark

# Build rule for target.
FaceLandmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FaceLandmark
.PHONY : FaceLandmark

# fast build rule for target.
FaceLandmark/fast:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/build
.PHONY : FaceLandmark/fast

src/Pfld.o: src/Pfld.cpp.o

.PHONY : src/Pfld.o

# target to build an object file
src/Pfld.cpp.o:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/Pfld.cpp.o
.PHONY : src/Pfld.cpp.o

src/Pfld.i: src/Pfld.cpp.i

.PHONY : src/Pfld.i

# target to preprocess a source file
src/Pfld.cpp.i:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/Pfld.cpp.i
.PHONY : src/Pfld.cpp.i

src/Pfld.s: src/Pfld.cpp.s

.PHONY : src/Pfld.s

# target to generate assembly for a file
src/Pfld.cpp.s:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/Pfld.cpp.s
.PHONY : src/Pfld.cpp.s

src/UltraFace.o: src/UltraFace.cpp.o

.PHONY : src/UltraFace.o

# target to build an object file
src/UltraFace.cpp.o:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/UltraFace.cpp.o
.PHONY : src/UltraFace.cpp.o

src/UltraFace.i: src/UltraFace.cpp.i

.PHONY : src/UltraFace.i

# target to preprocess a source file
src/UltraFace.cpp.i:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/UltraFace.cpp.i
.PHONY : src/UltraFace.cpp.i

src/UltraFace.s: src/UltraFace.cpp.s

.PHONY : src/UltraFace.s

# target to generate assembly for a file
src/UltraFace.cpp.s:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/UltraFace.cpp.s
.PHONY : src/UltraFace.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/FaceLandmark.dir/build.make CMakeFiles/FaceLandmark.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FaceLandmark"
	@echo "... edit_cache"
	@echo "... src/Pfld.o"
	@echo "... src/Pfld.i"
	@echo "... src/Pfld.s"
	@echo "... src/UltraFace.o"
	@echo "... src/UltraFace.i"
	@echo "... src/UltraFace.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

